### ISSUE TITLE
Crashes with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chinenual** [chinenual/synergize#26]
During recent testing, Synergize has been crashing at unpredictable times - appears to be related to the zeroconf daemon thread.  New since 2.2.0?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13a6a3f]

goroutine 60 [running]:
github.com/brutella/dnssd.probeAtInterface(0x164fe00, 0xc0011cd500, 0x1650f00, 0xc0011f4640, 0xc00016e540, 0x31, 0x158df7c, 0x9, 0x158c67e, 0x5, ...)
	/Users/tynor/src/dnssd/probe.go:179 +0x86f
github.com/brutella/dnssd.probe(0x164fe00, 0xc0011cd500, 0x1650f00, 0xc0011f4640, 0xc00016e540, 0x31, 0x158df7c, 0x9, 0x158c67e, 0x5, ...)
	/Users/tynor/src/dnssd/probe.go:114 +0x337
github.com/brutella/dnssd.probeService(0x164fe00, 0xc0011cd500, 0x1650f00, 0xc0011f4640, 0xc00016e540, 0x31, 0x158df7c, 0x9, 0x158c67e, 0x5, ...)
	/Users/tynor/src/dnssd/probe.go:61 +0x35b
github.com/brutella/dnssd.ReprobeService(0x164fe00, 0xc0011cd500, 0xc00016e540, 0x31, 0x158df7c, 0x9, 0x158c67e, 0x5, 0xc00012cc90, 0x9, ...)
	/Users/tynor/src/dnssd/probe.go:49 +0x14c
github.com/brutella/dnssd.(*responder).reprobe(0xc0001cc400, 0xc000128170)
	/Users/tynor/src/dnssd/responder.go:348 +0x13b
created by github.com/brutella/dnssd.(*responder).respond
	/Users/tynor/src/dnssd/responder.go:248 +0x474

```

**Comment by chinenual** [comment]
Fixed by commenting out a Debug.Printf statement in the dnssd library. 

Bug raised on the underlying library at https://github.com/brutella/dnssd/issues/22
